config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "items#index"
  resources :familys, only:[:new, :create] do
    resources :items, only:[:new, :create, :edit, :update, :destroy] do
      collection do
        get 'index_request'
        put 'update_request'
        get 'index_destroy'
      end
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :shop
  belongs_to :category
  belongs_to :family
  #belongs_to :scomplete
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:index]


  def index
    @items = Item.where(family_id: current_user.family_id).where.not(user_id: nil)
  end

  def new
    @item_shop_category = ItemShopCategory.new
  end

  def create
    @item_shop_category = ItemShopCategory.new(item_shop_category_params)
    if @item_shop_category.valid?
      @item_shop_category.save
      redirect_to root_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def update
    checked_item_ids = params[:item_ids]
    if checked_item_ids.present?
      checked_item_ids.each do |item_id|
        item = Item.find_by(id: item_id)
        item.update(user_id: nil) if item.present?
      end
      redirect_to root_path
    end
  end

  def index_request
    @items = Item.where(family_id: current_user.family_id)
    @categories = Category.all
  end

  def update_request
    checked_item_ids = params[:item_ids]
    if checked_item_ids.present?
      checked_item_ids.each do |item_id|
        item = Item.find_by(id: item_id)
          item.update(user_id: current_user.id) if item.present?
        end
      end
      redirect_to root_path
  end

  def index_destroy
    @items = Item.where(family_id: current_user.family_id)
  end

  def destroy
    checked_item_ids = params[:item_ids]
    if checked_item_ids.present?
      checked_item_ids.each do |item_id|
        item = Item.find_by(id: item_id)
          item.destroy if item.present?
        end
      end
      redirect_to root_path
  end

  private

  def item_shop_category_params
    params.require(:item_shop_category).permit(:item_name, :unit_quantity, :price, :shop_name, :category_name, :remarks).merge(family_id: params[:family_id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<%= render "shared/header" %>
  <div class='item-contents'>
    <div class="title-block">
      <div class='title'>買い物リスト</div>
    </div>


    <div class='item-card'>
      <div class=item-category>
        カテゴリ
      </div>
      <div class=item-name>
        商品名
      </div>
      <div class=item-price>
        単価
      </div>
      <div class=item-quantity>
        購入数
      </div>
      <div class=item-shop>
        店舗
      </div>
      <div class=item-remarks>
        備考
      </div>
      <div class="item-done-checkbox">
      </div>
    </div>


    <%= form_with model: @items, url: family_item_path(family_id: current_user.family_id, id: @items), method: :put, local: true do |f| %>
      <ul class='item-lists'>
        <% @items.each do |item| %>
          <li class='list'>
          <div class='item-card'>
            <div class=item-category>
              <%= item.category.category_name %>
            </div>
            <div class=item-name>
              <%= item.item_name %>
            </div>
            <div class=item-price>
              <%= item.price %>
            </div>
            <div class=item-quantity>
              <%= item.unit_quantity %>
            </div>
            <div class=item-shop>
              <%= item.shop.shop_name %>
            </div>
            <div class=item-remarks>
              <%= item.remarks %>
            </div>
            <div class="item-done-checkbox">
              <%= check_box_tag "item_ids[]", item.id %>
              <%= label_tag "item_ids_#{item.id}", "購入済み" %>
            </div>
          </div>
          </li>
        <% end %>
      </ul>
      <div class="sell-btn-block"><%= f.submit "購入済み確定" ,class:"sell-btn" %></div>
    <% end %>
  </div>

app/views/items/index_destroy.html.erb
<%= render "shared/header" %>
  <div class='item-contents'>
    <div class="title-block">
      <div class='title'>商品削除</div>
    </div>

    <div class='item-card'>
      <div class=item-category>
        カテゴリ
      </div>
      <div class=item-name>
        商品名
      </div>
      <div class=item-price>
        単価
      </div>
      <div class=item-quantity>
        購入数
      </div>
      <div class=item-shop>
        店舗
      </div>
      <div class=item-remarks>
        備考
      </div>
      <div class="item-done-checkbox">
      </div>
    </div>

    <%= form_with model: @items, url: family_item_path(family_id: current_user.family_id, id: @items), method: :delete, local: true do |f| %>
      <ul class='item-lists'>
        <% @items.each do |item| %>
          <li class='list'>
            <div class='item-card'>
              <div class=item-category>
                <%= item.category.category_name %>
              </div>
              <div class=item-name>
                <%= item.item_name %>
              </div>
              <div class=item-price>
                <%= item.price %>
              </div>
              <div class=item-quantity>
                <%= item.unit_quantity %>
              </div>
              <div class=item-shop>
                <%= item.shop.shop_name %>
              </div>
              <div class=item-remarks>
                <%= item.remarks %>
              </div>
              <div class="item-done-checkbox">
                <%= check_box_tag "item_ids[]", item.id %>
                <%= label_tag "item_ids_#{item.id}", "削除選択" %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
      <div class="sell-btn-block"><%= f.submit "削除する" ,class:"sell-btn" %></div>
    <% end %>
  </div>

app/views/items/index_request.html.erb
<%= render "shared/header" %>
  <div class='item-contents'>
    <div class="title-block">
      <div class='title'>買い物リスト登録</div>
    </div>

    <div class='item-card'>
      <div class=item-category>
        カテゴリ
      </div>
      <div class=item-name>
        商品名
      </div>
      <div class=item-price>
        単価
      </div>
      <div class=item-quantity>
        購入数
      </div>
      <div class=item-shop>
        店舗
      </div>
      <div class=item-remarks>
        備考
      </div>
      <div class="item-done-checkbox">
      </div>
    </div>

    <%= form_with model: @items, url: update_request_family_items_path(family_id: current_user.family_id, id: @items), method: :put, local: true do |f| %>
      <ul class='item-lists'>
        <% @items.each do |item| %>
          <li class='list'>
            <div class='item-card'>
              <div class=item-category>
                <%= item.category.category_name %>
              </div>
              <div class=item-name>
                <%= item.item_name %>
              </div>
              <div class=item-price>
                <%= item.price %>
              </div>
              <div class=item-quantity>
                <%= item.unit_quantity %>
              </div>
              <div class=item-shop>
                <%= item.shop.shop_name %>
              </div>
              <div class=item-remarks>
                <%= item.remarks %>
              </div>
              <div class="item-done-checkbox">
                <%= check_box_tag "item_ids[]", item.id %>
                <%= label_tag "item_ids_#{item.id}", "登録する" %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
      <div class="sell-btn-block"><%= f.submit "更新する" ,class:"sell-btn" %></div>
    <% end %>
  </div>

app/views/items/new.html.erb
<%= render "shared/header" %>

  <div class="item-contents">
    <div class="title-block">
      <div class="title">商品の情報を入力</div>
    </div>

    <div class='item-card'>
      <div class=item-category>
        カテゴリ
      </div>
      <div class=item-name>
        商品名
      </div>
      <div class=item-price>
        単価
      </div>
      <div class=item-quantity>
        購入数
      </div>
      <div class=item-shop>
        店舗
      </div>
      <div class=item-remarks>
        備考
      </div>
    </div>

    <%= form_with model: @item_shop_category, url:family_items_path , local: true do |f| %>
    <div class="item-card">
      <%#= f.text_area :category_name, class:"item-category", id:"item-info" %>
      <%= f.collection_select :category_id, Category.all, :id, :category_name  %>
      <%= f.text_area :item_name, class:"item-name", id:"item-name", maxlength:"40" %>
      <%= f.text_area :price, class:"item-price", id:"item-info" %>
      <%= f.text_area :unit_quantity, class:"item-quantity", id:"item-info" %>
      <%= f.text_area :shop_name, class:"item-shop", id:"item-info" %>
      <%= f.text_area :remarks, class:"item-remarks", id:"item-info" %>
    </div>

    <%# 下部ボタン %>
    <div class="sell-btn-block">
      <%= f.submit "新規商品登録する" ,class:"sell-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>